server:
  port: 8080

zeebe:

  # engine options: 'embedded' (EZE) / 'remote' (external broker via Spring Zeebe)
  engine: embedded

  client:
    broker.gatewayAddress: 127.0.0.1:26500
    security.plaintext: true

    # Disable the Zeebe-Spring client to avoid configuration issues with the embedded engine.
    enabled: false

    worker:
      hazelcast:
        connection: localhost:5701
        connectionTimeout: PT1M
        ringbuffer: zeebe
        connectionInitialBackoff: PT15S
        connectionBackoffMultiplier: 2.0
        connectionMaxBackoff: PT30S

  clock:
    endpoint: 127.0.0.1:9600/actuator/clock

  connectors:
    # connector mode options: 'active' (as job workers) / 'passive' (trigger manually in process)
    mode: passive
    secrets:
    #  - name: SLACK_OAUTH_TOKEN
    #    value: my-slack-oauth-token

spring:
  datasource:
    url: jdbc:h2:mem:zeeqs;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  graphql:
    websocket:
      path: /graphql

    # enable GraphiQL inspection tool by default
    graphiql:
      enabled: true
